version: "3.7"

services:
  jenkins:
    image: jenkins/cdc
    ports:
      - "9080:8080"
    environment:
      - JENKINS_ADMIN_ID=cdc
      - JENKINS_ADMIN_PASSWORD=pwd11
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: .